stellar/docs

docs/gateway-list.md

Add dividend rippler to gateway-list

Add dividend rippler to gateway-list

---

CONTRIBUTING.md

Fix typo in CONTRIBUTING.md and add Community Guidelines to CONTRIBUTING.md

Add link to Community Guidelines and fix typo

---

README.md

Remove dead links in readme. Add links to client tutorial, old-docs folder, and contribution guide. Fixes Issue #39

Update dead links in readme.

---

old-docs/Adding-Multiple-Currencies.md

Update link for trust lines

---

old-docs/Adding-Multiple-Currencies.md

Update link for gateway introduction

---

learn/concepts/accounts.md

just fixing a broken link to stellar.txt

fix stellar.txt link

---

validators.md

"snippits" is likely a typo,"snippets" is correct.

add my validator node ,

---

other/stellar-core-validator-example.cfg

also switched to http instead of https as data is validated when catching up

switched sdf watcher nodes to use curl

---

validators.md

adding stellar.w00kie.com

---

learn/integration-guides/exchange.md

Fixes small errors and emphasize that some db queries must be atomic.
One additional question:
> When a user wants to deposit lumens in your exchange, instruct them to send XLM to your hot wallet address with the customerID in the memo field of the transaction.
Shouldn't users send to cold wallet? Let's say someone sends large amount of XLM and then hot wallet is compromised. In this case, exchange will lose more money.

Exchange.md refactoring

---

learn/integration-guides/building-blocks/account-management.md
learn/integration-guides/exchange.md
learn/integration-guides/gateway.md

Close https://github.com/stellar/docs/issues/79

add the horizon endpoints hit in the comments of the guides

---

learn/readme.md

Fix typo in readme

---

learn/readme.md

I believe this should be capitalized since it's the start of a sentence.

correct capitalization

---

learn/integration-guides/gateway.md

* Added DB transactions where needed.
* Added custom assets.
* Switched from `setInterval` to `setTimeout` to prevent from double spending.
* Fixed formatting issues.

Fix gateway guide

---

learn/integration-guides/exchange.md
learn/integration-guides/gateway.md

* `cursor` should be `VARCHAR` not `INT`,
* `cursor` parameter shouldn't be added to request if doesn't exist.

Change how cursor works in integration guides

---

learn/concepts/scp.md

changed video link to jump right to the talk.

added better video link

---

learn/concepts/accounts.md
learn/concepts/list-of-operations.md

This contains a lot of whitespace fixes because my editor does them automatically and I decided to let them go through.

Flags note

---

learn/concepts/assets.md

Includes two things:
- Switch to `##` for base header size
- Detailed section about amount precision
Finishes https://github.com/stellar/docs/issues/76

add detailed information about amount precisions and representation

---

learn/concepts/federation.md

This changes small things and improves a bit of the wording. I couldn't find major things to improve upon

add small improvements to federation doc

---

other/things-to-build.md

We say "just ask us" but don't clarify how to do so - this will add a few clear/actionable options.

clarify contact info

---

learn/get-started/get-started.md
learn/readme.md

I created a short article/tutorial about how to actually get started: generating keypair, testnet account, building and submitting first transaction. I wrote it because right now it's hard to find an article explaining first steps and general concepts. It contains a lot of links to concepts and APIs reference and will appear under "Get started" section.
If something's not clear feel free to update it/comment this PR.
I also updated main file to link to the updated list of SDKs (including Java SDK so close https://github.com/stellar/docs/issues/96).

Get Started article

---

learn/concepts/transactions.md
learn/concepts/versioning.md

In the future, we should strive to do things this way instead of with lists so that they can be linked to directly

Make things linkable

---

learn/integration-guides/anchor.md

includes changing file name to /anchor

Change gateway to anchor

---

learn/integration-guides/anchor.md

NOTE: instances of 'hot wallet' in the code itself still remain. 
Also changed title to remove 'gateway'

Change 'hot wallet' to 'base account'

---

tools/readme.md

remove xdr viewer link

---

learn/concepts/accounts.md

add clarification on homedomain and an example

---

learn/concepts/transactions.md

fix indentation in transactions page

---

learn/get-started/readme.md

Uploaded the new diagram to the media gallery in WP, replaced the old link with the new one here.

Add revised ecosystem diagram

---

learn/get-started/create-account.md

Trying to resolve @irisli’s concerns from https://github.com/stellar/docs/commit/e5a5038fae03b73b2135cb97003b3324ac7e497c#commitcomment-18066149
Does this read better to you, Iris?

Reword relationship between account ID and public key.

---

validators.md

This adds a new validator (sparrow_tw) to validators.md.

Added new node to validators.md

---

guides/get-started/create-account.md

Now that https://github.com/stellar/js-stellar-sdk/pull/67 is shipped, we can make some examples a little simpler. (Some guides that also need this fix haven't been merged yet, so I've also updated their PRs, e.g. #154)

Simplify account loading examples in JS

---

guides/get-started/transactions.md
guides/security.md

**WORK-IN-PROGRESS—not ready to merge**
This is a new guide to basic security practices with Stellar. At the moment, it’s mainly a *very* rough draft with lots of holes that was originally written over on Google Docs. All further work and discussion will be here.
Things that need to be addressed here:
There’s also sort of an open question as to organization. Right now this is a flat list, but could be organized into sections, maybe like:
- Accounts
- Secure offline accounts
- Require multiple authorizations or signers
- Ensure assets are revocable
- Core
- Securing a Stellar Core Instance
- Keep Up to Date with Security Patches
- Handling Problems
- What if an account’s keys are compromised?
- What if there’s a bug in Stellar’s code?
Is that a better way to organize this doc?

Security Guide

---

guides/concepts/fees.md

Add term for fee pool vis-a-vis training

Add "fee pool"

---

guides/concepts/inflation.md

Add anchor for term "inflation"

---

other/stellar-core-validator-example.cfg
validators.md

Today we started the quantoz.com validating node. This PR adds the configuration.

Add quantoz.com validator node configuration

---

guides/anchor/3-federation-server.md

Changed TLS certificate config

---

CONTRIBUTING.md

- moved "Minor Changes" section up, under "Getting Started",
where it's easier to see you don't need to first create an issue
- minor spacing, grammar, and formatting changes

doc Update CONTRIBUTING.md

---

validators.md

umbrel validator is up

---

guides/get-started/create-account.md

Fixed a few things in the go examples that makes them runnable.

Fixed get-started documentation for go code

---

guides/anchor/2-bridge-server.md

modify recieve callback http method

---

guides/anchor/2-bridge-server.md

To reflect the change in the bridge_example.cfg
....this was a change made a little while back due to a port collision between bridge and compliance (both used 8001)

Changed ports from 8001 to 8006

---

validators.md

New Validator

---

reference/readme.md

New 100% fully functional SDK for .NET 2.0 added.  Prior C# library already listed from QuantozTechnology only offers a small subset of functionality.  May want to indicate that somehow to avoid confusion.

Added new SDK for .NET Core 2.0

---

validators.md

Updating validators in preparation for adding FairX as a validator for USA-West Coast.

Updating validators

---

guides/get-started/transactions.md

Close https://github.com/stellar/docs/issues/245

Process when transaction submisssion failures occur

---

guides/get-started/create-account.md

Update minimum balance from 20 lumens to 1 lumen.

doc Update minimum account balance

---

guides/get-started/create-account.md

AccountRequestBuilder.account no longer takes accountId

Update Java getBalance example for current API

---

guides/concepts/multi-sig.md

Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

Fix multi-sig wording

---

validators.md

Add validator used by [Stellar Pool](https://www.stellarpool.net).
It runs on a host located in Europe.

Add stellarpool.net validator

---

validators.md

Lots of other validators to choose from now :)

remove ZuluCrypto validator

---

guides/concepts/transactions.md

Transaction errors

---

validators.md

Remove stellarpool.net validator

---

validators.md

We are adding 5 Stronghold Validators across the world.

Adding Stronghold Validators 1 through 5

---

guides/exchange.md

Last line: I think anchor guide has moved to:
https://github.com/stellar/docs/blob/master/guides/anchor/readme.md

Link to anchor guide leads to 404. Change link

---

guides/issuing-assets.md

None of this should merge until the next Java SDK release; mainly just creating a branch where relevant updates can be gathered as changes land in the SDK.

WIP: Example updates for new Java SDK features

---

validators.md

Republic is hosting a Stellar validator, and plans to maintain it long term.

Add Republic's public validator

---

validators.md

Please, update validators.md 

---

validators.md

Added peering host names, full/basic validator description.

Updated stellar.chris.network

---

guides/walkthroughs/stellar-smart-contracts.md

Uncertain if I understood this correctly, but I believe the new signers should be party A and party B

fix signers in tx 2 for the crowdfunding SC

---

guides/hardware.md

this is taken from the previously reviewed hardware requirements google doc

added hardware requirements

---

validators.md

added jfl validator to validators.md
I put in down at the bottom in the off-line section for now (it is up and on-line).
once it gets added and shows as on-line, i'll move it up into the on-line section.

added jfl validator

---

guides/walkthroughs/stellar-smart-contracts.md

Suggesting adding 'other' to specify the additional accounts in the explanation.

fixing missing subject qualifier

---

guides/get-started/transactions.md

He-yo
I've added Go examples for sending money in [Transactions](https://www.stellar.org/developers/guides/get-started/transactions.html) step in getting started guide. 
Solves issue #243

Add Go examples for sending & streaming payments

---

guides/concepts/multi-sig.md

added info to the doc about our discussion on excessive signatures

info about fail transactions with too many signatures

---

validators.md

Updated location and node hostnames.

Updated location and node names

---

guides/exchange.md

.../anchor/readme.html   -->   /anchor/index.html

Fix anchor guide link

---

guides/concepts/multi-sig.md
guides/concepts/transactions.md

added clarification on low threshold requirement for processing transactions

---

README.md

- fixed missing words
- fixed GitHub, Markdown capitalisation
- minor English grammar improvements

doc: README typos, capitalisation

---

validators.md

Adding our validator to the list.

Added Collegecoin validator

---

validators.md

Added Cowrie Validator

---

guides/exchange.md

I changed non-native to non-lumen and generally used the framing of 'token' more widely per a suggestion from Nikhil and Christian. Generally, it's not super intuitive that native asset = XLM. I also made some syntax changes.

Update syntax and change asset to token

---

guides/walkthroughs/how-to-complete-stellar-toml.md

Add required field for asset issuers to specify whether their token is anchored.  This reflects an addition to SEP 0001.

add is_asset_anchored to how-to-complete-stellar-toml

---

guides/attachment.md

it's to its

---

guides/anchor/2-bridge-server.md

Changed (wrong) port number 8001 to 8006 in the javascript snippet for sending a payment.

Update 2-bridge-server.md, fixed wrong port number in doc

---

validators.md

also sorted the validator list

Updated validator information for SDF

---

software/known-issues.md

I figured we should start a document to centralize some knowledge around complex issues

Initial commit for "known issues"

---

guides/concepts/test-net.md

Add reset cadence for the testnet.

---

validators.md

Add one more validator from Goodx Network de2.stellar.goodx.network

New Validator added

---

guides/walkthroughs/stellar-smart-contracts.md

Cleaned most lines up along with formatting, capitalization, etc.

Update formatting on Stellar Smart Contracts.

---

validators.md

Adding stellar.sui.li to validators list

---

guides/get-started/create-account.md

Rewrite the JS examples for creating an account with await so people can paste all the code into a console and run it without having to deal with async code.
Fixes https://github.com/stellar/js-stellar-sdk/issues/115.

JS Create account changes

---

reference/readme.md

Repo was read-only, no commits in last 9 months.

Remove apparently unmaintained second C# library

---

guides/concepts/list-of-operations.md

The description of how to delete a trustline was missing.

change trust -> set Limit to 0 to delete trustline

---

guides/anchor/2-bridge-server.md
guides/attachment.md
guides/channels.md
guides/exchange.md
guides/get-started/transactions.md

Also cleaned up some formatting on various lines.
The rest of these were contributed and merged in with #436.
Fixes #431.

Add .setTimeout to all TransactionBuilder examples.

---

guides/walkthroughs/securing-web-projects.md

Simple checks could have prevented the MyEtherWallet DNS hack, and the BlackWallet client-side script injection; this guide covers them and more.
As more projects are released, we should publish basic guidelines that outline basic web-sec standards for people building Stellar apps. We shouldn't be the authority on this, but we should cover important concepts for Stellar-app developers to ensure our ecosystem stays healthy.

Add security guide for web-based projects

---

guides/concepts/exchange.md
guides/concepts/list-of-operations.md
guides/concepts/operations.md
guides/walkthroughs/bifrost-server-setup.md
guides/walkthroughs/custom-assets.md
guides/walkthroughs/stellar-smart-contracts.md

* Change ManageOffer -> ManageSellOffer
* Change CreatePassiveOffer -> CreatePassiveSellOffer
* Add ManageBuyOffer
Fixes #454.

Add operations introduced in Protocol 11.

---

validators.md

Hello!
I would like to add our new validator to the list, please.
Thanks!
Could someone please review and merge?

Added new COINQVEST Full Validator to validators.md

---

guides/compliance-protocol.md

Add note on gostellar.org in the compliance protocol.

---

guides/concepts/exchange.md

Add section on Price in the DEX docs.

---

guides/get-started/create-account.md

Add Create Account op info in getting started.

---

guides/get-started/create-account.md
guides/get-started/transactions.md

Reformat the file and add an initial paragraph pointing to the Stellar Lab when a user is getting started.
Fixes #153.

Add notes on Stellar lab to getting started.

---

guides/concepts/list-of-operations.md

Fix specification of allow trust type.

---

guides/concepts/transactions.md

Closes #104, 3+ years in the making.

Add small section on transaction envelopes.

---

guides/concepts/list-of-operations.md

Add trust self error codes to ops docs.

---

guides/get-started/transactions.md

Remove anchor guide link from getting started.

---

guides/issuing-assets.md

Add section on redeeming assets.

---

guides/concepts/list-of-operations.md

Make the language consistent for describing ops.

---

guides/concepts/networks.md
guides/concepts/transactions.md

Fixes #69. This is definitely a first pass at this, so definitely up for any suggestions that folks may have.

Add concept doc on networks in Stellar.

---

guides/compliance-protocol.md
guides/walkthroughs/how-to-complete-stellar-toml.md

Update the compliance doc to SEP-0003, TOML doc to SEP-0001V2

---

guides/things-to-build.md

This page was great already, I just made a few small changes in spelling, spacing, grammar, etc. for consistency and correctness.

doc Update guides/things-to-build.md

---

guides/concepts/operations.md
guides/concepts/transactions.md

Add info on when sequence numbers are changed.

---

validators.md

Remove smoove.net nodes

---

guides/walkthroughs/how-to-complete-stellar-toml.md

Give some guidance on what the ORG_LOGO should be.  Ideally issuers could create multiple resolutions for different use cases, but that might be overkill.  It is good to give some guidance to hopefully keep some uniformity in the ecosystem.

Add ORG_LOGO recommendations

---

guides/concepts/list-of-operations.md
guides/concepts/operations.md

For 2 operations-related docs:
- Removed inflation
- Added path payment strict send
- Change path payment to path payment strict receive

Rice2000 protocol12 operations

---

guides/concepts/fees.md

The Fee Pool section still says that fees are redistributed via inflation. 
Open to different ways of describing what happens but wanted to get it updated.

Update fee pool information

---

guides/walkthroughs/connect-to-wallets.md

Former link (https://www.stellar.org/developers/guides/how-to-complete-stellar-toml.html) was broken

Updated link to stellar-toml.md guide.

---

other/stellar-core-validator-example.cfg

Fixes #539
This was changed in https://github.com/stellar/stellar-core/pull/2142

Update stellar-core CLI format

---

guides/compliance-protocol.md
guides/concepts/test-net.md

This change update links that not work correctly.

Update links in Testnet

---

guides/get-started/transactions.md

Per stellar/js-stellar-sdk#479, the example code here doesn't work.

Fix incorrect example

---

guides/concepts/accounts.md

'can be set' was confusing, the values will be set to true or false, but if its immutable it cannot be changed

Clarify authorization immutable meaning

---

guides/concepts/exchange.md

> Each stack is **the the** set of orders...
> ...on both sides of a trading pair **as as** _selling_.

Remove duplicate words

---

guides/issuing-assets.md

All examples have been tested in the test network.

Add examples for issuing assets using the Stellar Python SDK.

---

guides/get-started/create-account.md
guides/get-started/transactions.md
guides/issuing-assets.md
translations/pt-BR/guides/get-started/create-account.md
translations/pt-BR/guides/get-started/transactions.md
translations/pt-BR/guides/issuing-assets.md

The Java examples are out of date and do not match the current API of the Java SDK. 
https://stellar.stackexchange.com/questions/4078/receiving-baseencodingexception-when-signing-transaction-using-testnet-invalid

Update Java code examples

---

reference/readme.md

Please add the new flutter sdk to the list of community-maintained libraries.

add flutter sdk

---

guides/concepts/list-of-operations.md

https://stellar.stackexchange.com/questions/4381/can-not-delete-create-passive-sell-offer

correct passive offer docs
