stellar/docs

README.md

I added a deprecation notice on the api-docs section of the README.
The change on the contribution line is a whitespace fix.

update README deprecation notice

---

learn/readme.md

I suggest that we add the community-built Python library as a tangible example, and as a CTA of somewhere to contribute. Also nice to feature it as a thank you to the awesome community members who built it!

 add the community Python library

---

beyond-code/readme.md

Now links directly to the Stellar tag on Stack Exchange

change stack overflow link

---

learn/readme.md

This is so that people do not get confused and start reading interstellar docs when the sdk or Horizon docs are more what they need.

remove interstellar from root learn page

---

learn/integration-guides/exchange.md

Since we're using "secret key" rather than "seed," I've revised the code sample. H/t to @irisli for the suggestion.

change seed to secret key in code framework

---

learn/readme.md

This is partially because the content of the old page will be subsumed into the getting started guide in #136 and partially because this just needs to be a decent intro to this part of the site.

Re-write of guides landing page

---

learn/get-started/create-account.md
learn/get-started/transactions.md

Mostly typography: `**` for `<strong>` (unless there was a specific reason for that, @jessica-collier?) and smart apostrophes.
Also fixes the text of the “back” link on the last page of getting started so refers to the right page (it linked to the previous page—create account—but described the first page—network overview).

Very minor cleanup tweaks

---

learn/get-started/transactions.md

Since the security guide doesn’t actually exist in the developers site yet, we probably shouldn’t link to it!
(I guess I need to convert that draft to Markdown and make a PR for it, but is it really quite ready yet?)
@bartekn @jessica-collier

Remove link to security guide (it doesn't exist yet)

---

guides/concepts/ledger.md

We had some places that noted stroops when it should have been lumens and vice versa.

Fix denominations for lumens/stroops in ledgers doc

---

guides/concepts/xdr.md

Fixes #107.
This is basically a copy of the XDR doc from the Horizon repo, with some language tweaks and an added description of *why* XDR is used.

Add XDR concept doc

---

guides/concepts/list-of-operations.md

Fix typo and trailing spaces in list of operations

---

software/readme.md

Looks like a bunch of these links were changed recently, but several are broken.

Fix broken links to software code and releases

---

guides/concepts/federation.md
guides/things-to-build.md

It looks like the federation server moved from the https://github.com/stellar/federation repo to the https://github.com/stellar/go repo, so this just updates all thinks (that I could find) in the docs so people don't land on a page that says "DEPRECATED!"

Update federation server source code URLs

---

guides/compliance-protocol.md

Mainly this is the memo convention link, but one other was incorrect.

Fix broken links in Compliance Protocol doc

---

guides/concepts/federation.md

* Changed memo_hash encoding from `base32` to `base64`.  `base32` has multiple value -> character mappings what can be confusing. Additionally, horizon server is using `base64` encoding for memo hash values.
* Improved request/response details.
* Added "Caching" section. See https://github.com/stellar/go-private/issues/9#issuecomment-267588296.

Federation doc updates

---

guides/get-started/create-account.md

`pair.getSecretSeed()` returns a char array, so conversion to `String` is required to get the output that the comment indicates.

create-account java: convert char[] to String

---

guides/attachment.md
guides/compliance-protocol.md
guides/memo-preimage.md

After talking with a partner who wants to implement Compliance Protocol I realized that this document can be improved:
* I added example requests/responses.
* I added more information on requests format.
* I removed features that aren't there yet (ex. `ENCRYPTION_KEY`, `simple_aml`)
I also found some things that needs to be changed:
* Stellar Memo convention still links to the old spec which isn't used in production. I think we need to describe new Memo convention in a separate doc.
* I noticed this commit: https://github.com/stellar/bridge-server/commit/9e251b6c75c2170310ac79eeefa837efd7778777 It wasn't clear which value should be used in `route` parameter. This needs to be specified in this doc.
* This specification is still not clear on sequence number of `tx` sent in auth request and …

Compliance doc updates

---

guides/anchor/3-federation-server.md

Current implementation supports GET only, but javascript example uses POST, which may cause confusion

Javascript example GET

---

guides/get-started/transactions.md

Use to say `Return`, which is invalid JavaScript.

doc: downcase JavaScript `return`

---

guides/anchor/2-bridge-server.md

In the prebuilt binaries (which we're using in the Guides), the name of
the config file is expected to be bridge.cfg not config_bridge.toml as
stated in the Guides. This change fixes it.

Correct bridge config filename

---

other/stellar-core-validator-example.cfg

There two have very old ledgers - at about 50% of current history
Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

remove old history archives

---

software/readme.md

keeping all the docs in sync. no more planned changes here.
planning to merge this once https://github.com/stellar/go/pull/93 is merged

make "Software" tab in docs point to the new horizon location

---

guides/concepts/multi-sig.md

I'm not sure if the changes here are fully correct; it was not clear to me how this worked, so I've proposed some changes to clarify. It's mostly around greater than vs. greater than or equal to behavior for thresholds, and how the 0-weight case is handled (last example).
- Added some clarifying documentation around thresholds
- fixed formatting of Threshold bullet points.

updated multi-sig.md

---

guides/anchor/readme.md

Current stellar.toml is linking to https://www.stellar.org/developers/guides/concepts/stellar-toml, giving a 404 Not Found.
Updated link to include ".html", https://www.stellar.org/developers/guides/concepts/stellar-toml.html.

Update stellar.toml link to fix 404 error

---

guides/concepts/stellar-toml.md

The examples in the stellar.toml guide consult the old location for stellar.toml. This updates the configuration snippets to the expected location.

doc: update locations for stellar.toml in examples

---

guides/anchor/3-federation-server.md

Stellar Account Viewer will not locate a stellar.toml file on a www subdomain, only on a naked domain.

remove www subdomain from stellar.toml location

---

guides/issuing-assets.md

The minimum balance was calculated using the base reserve, and from January 12 it was lowered to 0.5 XLM.
> 2. The base reserve (currently 0.5 XLM) is used in minimum account balances.
Quoted from [Official developers guides/concepts/fees](https://www.stellar.org/developers/guides/concepts/fees.html)

Reflect new 0.5 XLM Base Reserve Fee

---

guides/concepts/federation.md

`forward` type is described as a supported type but is not listed in the federation request form example.

Add missing forward type in request example

---

guides/concepts/assets.md

Added reference to allow trust operation and removed false statement that the asset can be sent back to the anchor with authorisation revoked. The issue was detected on testnet and we had an informal answer from Boris , quoting CTO, that the documentation is outdated

Change of assets.md documentation

---

guides/exchange.md

One thing missing from this exchange guide was a description of how an exchange may add non-native assets.
A few questions:
* At the top we define issuing account which is different from the issuing account I describe. Is this confusing?
* Is non-native assets the right word choice?

Update exchange.md -- adding non-native assets to an exchange

---

guides/exchange.md

As per Boris's recommendation, clarify that exchanges.md is a guide on how to "Add Stellar to your exchange" not on how to "Set up an exchange"
Since the title was changed, I also removed the h1 header tag at the top to remove title duplication.

Update set up an exchange title

---

guides/concepts/assets.md

After some discussions with Boris and other partner/user facing members of the team, I thought it might be a good idea to rewrite this section to make it a bit clearer how `Authorization_required` and `Authorization_revoke` work.
Essentially, I:
a) kept the current auth require and authorize revoke descriptions
b) made it clear that these flags are not set by default and to obtain these functionalities, the flags must be set
c) Added two example user flows to make it easier to understand how/why these flags may be used

describe auth revoke and auth require flow

---

guides/exchange.md

Responding to a note from a member of the community:
> I'm looking over the guide and I think sample code for adding a trustline is missing.
> 
> Would be great to get that in there. I'm talking to [someone] now and they need this. I think the code is below but maybe you could verify with one of the devs please?
> 
```
var Asset = new StellarSdk.Asset('ASSET', "ISSUER_ADDRESS");
transaction.addOperation(StellarSdk.Operation.changeTrust({
asset: Asset
}))
```

Add trustline example and note about auth required

---

guides/issuing-assets.md

It seems like the var was there for legacy reasons but now the Global constants are used in `setFlag`.

Remove unused var from example.

---

guides/get-started/readme.md

Fix README by adding "the" preceding the docker image.

---

guides/anchor/2-bridge-server.md
guides/anchor/4-compliance-server.md

`id` params is now required in bridge and compliance requests to support resending transactions (ex. in case of `pending` response).

Add id param to bridge, compliance requests

---

guides/concepts/list-of-operations.md
guides/issuing-assets.md

* Added a warning around the usage of AUTHORIZATION REVOCABLE.
* Set using a single transaction as a best practice.

Add warnings on auth in the asset issuance guide.

---

validators.md

Hello!
We'd like to add our validators to the list, please.
You can inspect the state of each validator by viewing the static info URLs (they update every minute):
-> https://finland.stellar.coinqvest.com/info.json
-> https://germany.stellar.coinqvest.com/info.json
The validators run with CATCHUP_COMPLETE=true and we've implemented two public history archives. Information on how to use the archives (along with our quorum configuration) is included in our stellar.toml:
-> https://www.coinqvest.com/.well-known/stellar.toml
Would it be a good idea to publish a list of known history archives along with the list of known validators on the dashboard and Stellar website in the future? Currently it is hard to find any independent history archives and all new validators basically have to use the …

Added COINQVEST Full Validators/History Archives

---

guides/get-started/transactions.md

Working through these examples, some of the snippets are out of sync with the main code body. Fixed.

sync examples + minor grammar

---

guides/walkthroughs/stellar-smart-contracts.md

@jedmccaleb this came up a while back when discussing our development of smart contracts, and how we don't have a back-compat strategy in place. Added it to the docs to make it explicit.

Add note regarding backward compatability of SSC's.

---

guides/issuing-assets.md

The newest sdk/api requires setTimeout. Update documentation to include it so users do not run into errors using the example.

Add setTimeout to JS examples in documentation

---

guides/concepts/multi-sig.md

Explain how too many valid signatures will result in a failed
transaction, primarily due to the performance costs it brings.
Fixes #387.

Add explanation for `TX_BAD_AUTH_EXTRA`.

---

guides/concepts/list-of-operations.md

Move the documentation links on the operations page to txnbuild over the old build library for Go.
Currently depends on #456; will rebase on master before merging in.

Fix go links

---

guides/get-started/transactions.md

A timeout or a time bound is required to build a transaction in the Java SDK.

Add setTimeout to Java send transaction example

---

guides/get-started/create-account.md

The Javascript account creation snippet will throw an error because await needs to be wrapped in an async function. Verified on node 12.4.0.

doc: Update Javascript account creation snippet.

---

guides/walkthroughs/how-to-complete-stellar-toml.md

When digging through some toml files I noticed a handful people are using jpg images or images without transparent backgrounds for their logo. 
I could be nitpicking, but I think we should suggest using logos with transparent backgrounds and certain file formats. Mostly to make developers and especially designers lives easier when pulling images from toml files. 
Also changed the example image to a goat icon with a transparent background.

Suggesting certain image types to include in toml file

---

guides/concepts/transactions.md

Minor update that polishes the text in the "Source Account" section.

doc: Fix typo on Transactions docs

---

guides/anchor/4-compliance-server.md
guides/walkthroughs/custom-assets.md

- remove link to outdate anchor guide from custom assets doc
- remove mysql from compliance server guide since it's not longer supported

doc fixes related to anchor guide

---

guides/anchor/3-federation-server.md
translations/pt-BR/guides/anchor/3-federation-server.md

Remove mention of MySQL in Federation docs, to bring the docs inline with stellar/go#1753 and future versions of Federation that are released.
Close stellar/go#1736.

Remove mentions of MySQL in Federation docs

---

guides/walkthroughs/stellar-smart-contracts.md

The link for Smart Contracts: 12 Use Cases for Business and Beyond was pointing to a dead URL.  Found the correct PDF that this link should be pointing to and corrected it.

Update link on Stellar-smart-contracts.md

---

guides/lumen-supply-metrics.md

It had a wrong url. It should be `https://www.stellar.org/developers/guides/lumen-supply-metrics.html`

Fixing the url on lumen-supply-metrics

---

validators.md

Not Slack....
Note that at some point, references to people via Slack identities in this document should also be changed as appropriate.

Point to validators channel, on Keybase now

---

guides/anchor/2-bridge-server.md
guides/anchor/3-federation-server.md
guides/anchor/4-compliance-server.md
guides/anchor/5-conclusion.md
guides/anchor/readme.md

People keep finding the legacy anchor guide even though it's not linked to from the docs.  This PR adds a deprecation notice to the top of each section.  A quick fix while we work on the new docs.

Add anchor guide deprecation notice

---

guides/get-started/transactions.md

The Python example was calling `set_timeout(10)` but the comment said it was a maximum of 3 minutes. Fix code to set timeout to 180 seconds.

Fix timeout in Python example

---

guides/get-started/readme.md
reference/readme.md
translations/pt-BR/guides/get-started/readme.md

Evil Martians (https://github.com/astroband/) have now taken ownership of the Ruby SDK. Update links to point at the [new repo location](https://github.com/astroband/ruby-stellar-sdk).

change Ruby links to point to astroband org

---

guides/exchange.md

While we decide if we want to port the exchange content to the new docs, remove the dead link to 'updated content' so as not to confuse anyone who needs to reference this page.

Removing bad 404 link to updated content
